### ISSUE TITLE
[Trouble-Shooting] docker enoent enoent: no such file or directory, open '/source/package.json'

### ISSUE THREAD

**Issue by EeeasyCode** [EeeasyCode/haru-hanjul#13]
서버 컨테이너에서 실행될 npm install이 package.json을 찾지 못해 발생하는 오류

[해결 방안] 
docker-compose.yml에 명시한 volumes의 경로를 재설정
```
haru:
    depends_on:
      - database
    build:
      context: ./server  # 빌드할 Dockerfile이 위치한 경로
    container_name: haru
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    expose:
      - "3000"           # 다른 컨테이너에게 3000번 포트 open
    volumes:
      **- ./server:/source # host <-> container의 source 디렉토리를 공유**
      - /source/node_modules 
    restart: "unless-stopped"
    networks:
    - haru-app
```

위 코드에서 bold 된 부분을 잘 설정해주어야 함.
local 디렉토리와 container 디렉토리를 공유하기 때문에 local 디렉토리의 경로와 container 디렉토리의 경로 둘 다 정확히 입력해주어야 함.
